#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: luotian520
    driver-class-name: com.mysql.jdbc.Driver